image: rburgst/java-openjfx

before_script:
  - chmod +x gradlew

build:
  stage: build
  script:
    - ./gradlew clean installDist
  artifacts:
    name: "RestaurantOrderingSystem"
    paths:
    - build/server/install/*
    - build/client/install/*
  allow_failure: false