/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.models.pojo;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Productpricefororder implements Serializable {

    private static final long serialVersionUID = -2120953702;

    private UInteger  productId;
    private UInteger  orderId;
    private Double    price;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public Productpricefororder() {}

    public Productpricefororder(Productpricefororder value) {
        this.productId = value.productId;
        this.orderId = value.orderId;
        this.price = value.price;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Productpricefororder(
        UInteger  productId,
        UInteger  orderId,
        Double    price,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.productId = productId;
        this.orderId = orderId;
        this.price = price;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public UInteger getProductId() {
        return this.productId;
    }

    public void setProductId(UInteger productId) {
        this.productId = productId;
    }

    public UInteger getOrderId() {
        return this.orderId;
    }

    public void setOrderId(UInteger orderId) {
        this.orderId = orderId;
    }

    public Double getPrice() {
        return this.price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Productpricefororder (");

        sb.append(productId);
        sb.append(", ").append(orderId);
        sb.append(", ").append(price);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
