/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.models.pojos;


import org.jooq.types.UInteger;

import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllergenLocalized implements Serializable {

    private static final long serialVersionUID = 1410875736;

    private UInteger  allergenId;
    private String    languageCode;
    private String    label;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public AllergenLocalized() {}

    public AllergenLocalized(AllergenLocalized value) {
        this.allergenId = value.allergenId;
        this.languageCode = value.languageCode;
        this.label = value.label;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public AllergenLocalized(
        UInteger  allergenId,
        String    languageCode,
        String    label,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.allergenId = allergenId;
        this.languageCode = languageCode;
        this.label = label;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public UInteger getAllergenId() {
        return this.allergenId;
    }

    public void setAllergenId(UInteger allergenId) {
        this.allergenId = allergenId;
    }

    public String getLanguageCode() {
        return this.languageCode;
    }

    public void setLanguageCode(String languageCode) {
        this.languageCode = languageCode;
    }

    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        return label;
    }
}
