/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.models.pojos;


import java8.util.stream.Collectors;
import java8.util.stream.StreamSupport;
import org.jooq.types.UInteger;

import javax.annotation.Generated;
import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

import static java8.util.stream.StreamSupport.stream;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Invoice implements Serializable {

    private static final long serialVersionUID = -852538769;

    private UInteger  id;
    private Byte      paid;
    private Timestamp createdAt;
    private Timestamp updatedAt;
    private List<Order> orders;

    public Invoice() {}

    public Invoice(Invoice value) {
        this.id = value.id;
        this.paid = value.paid;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Invoice(
        UInteger  id,
        Byte      paid,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.paid = paid;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public Byte getPaid() {
        return this.paid;
    }

    public void setPaid(Byte paid) {
        this.paid = paid;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Invoice (");

        sb.append(id);
        sb.append(", ").append(paid);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    public void setOrders(List<Order> orders) {
        this.orders = orders;
    }

    public List<Order> getOrders() {
        return orders;
    }

    public List<String> getWaiters() {
        return stream(getOrders()).map(Order::getWaiter).map(Waiter::getName).map(name -> name.split(" ")[0]).distinct().collect(Collectors.toList());
    }

    public UInteger getTable() {
        if(getOrders() == null)
            return null;
        return getOrders().stream()
                .map(Order::getTableId)
                .findFirst()
                .orElse(null);
    }

    public List<InvoiceEntry> getProductListInvoice(Language language) {
        if(getOrders() == null)
            return new ArrayList<>();

        List<InvoiceEntry> invoiceEntryList =
                        stream(Order.combineOrders(orders))
                        .map(ppfo ->
                                new InvoiceEntry(
                                        ppfo.getQuantity(),
                                        ppfo.getProductInLanguage(language).getLabel(),
                                        ppfo.getPricePerProduct().doubleValue(),
                                        ppfo.getTotalPriceOfProduct().doubleValue()
                                )
                        )

                .collect(Collectors.toList());
        return invoiceEntryList;
    }

    public BigDecimal getTotalPrice() {
        if(getOrders() == null)
            return null;
        BigDecimal total = StreamSupport.stream(orders)
                .map(Order::getTotalPriceOfOrder)
                .reduce(BigDecimal::add)
                .get();
        return total;
    }

    public static class InvoiceEntry {
        public final String productName;
        public final double productPrice, productPriceTotal;
        public final UInteger quantity;

        public InvoiceEntry(UInteger quantity, String productName, double productPrice, double productPriceTotal) {
            this.quantity = quantity;
            this.productName = productName;
            this.productPrice = productPrice;
            this.productPriceTotal = productPriceTotal;
        }
    }
}
