/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.models.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategory implements Serializable {

    private static final long serialVersionUID = -488526348;

    private UInteger id;
    private String   imageUrl;

    public ProductCategory() {}

    public ProductCategory(ProductCategory value) {
        this.id = value.id;
        this.imageUrl = value.imageUrl;
    }

    public ProductCategory(
        UInteger id,
        String   imageUrl
    ) {
        this.id = id;
        this.imageUrl = imageUrl;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public String getImageUrl() {
        return this.imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductCategory (");

        sb.append(id);
        sb.append(", ").append(imageUrl);

        sb.append(")");
        return sb.toString();
    }
}
