/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.models.pojos;


import org.jooq.types.UInteger;

import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductAllergen implements Serializable {

    private static final long serialVersionUID = 294400483;

    private UInteger  allergenId;
    private UInteger  productId;
    private Timestamp createdAt;
    private Timestamp updatedAt;
    private Allergen allergen;

    public ProductAllergen() {}

    public ProductAllergen(ProductAllergen value) {
        this.allergenId = value.allergenId;
        this.productId = value.productId;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public ProductAllergen(
        UInteger  allergenId,
        UInteger  productId,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.allergenId = allergenId;
        this.productId = productId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public UInteger getAllergenId() {
        return this.allergenId;
    }

    public void setAllergenId(UInteger allergenId) {
        this.allergenId = allergenId;
    }

    public UInteger getProductId() {
        return this.productId;
    }

    public void setProductId(UInteger productId) {
        this.productId = productId;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductAllergen (");

        sb.append(allergenId);
        sb.append(", ").append(productId);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }

    public void setAllergen(Allergen allergen) {
        this.allergen = allergen;
    }

    public Allergen getAllergen() {
        return allergen;
    }
}
