/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.models.pojos;


import org.jooq.types.UInteger;

import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductPriceForOrder implements Serializable {

    private static final long serialVersionUID = -1554895718;

    private UInteger  productId;
    private UInteger  orderId;
    private Double    pricePerProduct;
    private UInteger  quantity;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public ProductPriceForOrder() {}

    public ProductPriceForOrder(ProductPriceForOrder value) {
        this.productId = value.productId;
        this.orderId = value.orderId;
        this.pricePerProduct = value.pricePerProduct;
        this.quantity = value.quantity;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public ProductPriceForOrder(
            UInteger  productId,
            UInteger  orderId,
            Double    pricePerProduct,
            UInteger  quantity,
            Timestamp createdAt,
            Timestamp updatedAt
    ) {
        this.productId = productId;
        this.orderId = orderId;
        this.pricePerProduct = pricePerProduct;
        this.quantity = quantity;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public UInteger getProductId() {
        return this.productId;
    }

    public void setProductId(UInteger productId) {
        this.productId = productId;
    }

    public UInteger getOrderId() {
        return this.orderId;
    }

    public void setOrderId(UInteger orderId) {
        this.orderId = orderId;
    }

    public Double getPricePerProduct() {
        return this.pricePerProduct;
    }

    public void setPricePerProduct(Double pricePerProduct) {
        this.pricePerProduct = pricePerProduct;
    }

    public UInteger getQuantity() {
        return this.quantity;
    }

    public void setQuantity(UInteger quantity) {
        this.quantity = quantity;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductPriceForOrder (");

        sb.append(productId);
        sb.append(", ").append(orderId);
        sb.append(", ").append(pricePerProduct);
        sb.append(", ").append(quantity);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
