/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.models.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategoryLocalized implements Serializable {

    private static final long serialVersionUID = 572491746;

    private UInteger productCategoryId;
    private String   languageCode;
    private String   label;

    public ProductCategoryLocalized() {}

    public ProductCategoryLocalized(ProductCategoryLocalized value) {
        this.productCategoryId = value.productCategoryId;
        this.languageCode = value.languageCode;
        this.label = value.label;
    }

    public ProductCategoryLocalized(
        UInteger productCategoryId,
        String   languageCode,
        String   label
    ) {
        this.productCategoryId = productCategoryId;
        this.languageCode = languageCode;
        this.label = label;
    }

    public UInteger getProductCategoryId() {
        return this.productCategoryId;
    }

    public void setProductCategoryId(UInteger productCategoryId) {
        this.productCategoryId = productCategoryId;
    }

    public String getLanguageCode() {
        return this.languageCode;
    }

    public void setLanguageCode(String languageCode) {
        this.languageCode = languageCode;
    }

    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ProductCategoryLocalized (");

        sb.append(productCategoryId);
        sb.append(", ").append(languageCode);
        sb.append(", ").append(label);

        sb.append(")");
        return sb.toString();
    }
}
