/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.models.pojos;


import java8.util.stream.StreamSupport;
import org.jooq.types.UInteger;

import javax.annotation.Generated;
import java.io.Serializable;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategory implements Serializable {

    private static final long serialVersionUID = -1752109739;

    private UInteger  id;
    private String    imageUrl;
    private UInteger  locationId;
    private Timestamp createdAt;
    private Timestamp updatedAt;
    private List<ProductCategoryLocalized> productCategoryLocalized;

    public ProductCategory() {}

    public ProductCategory(ProductCategory value) {
        this.id = value.id;
        this.imageUrl = value.imageUrl;
        this.locationId = value.locationId;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public ProductCategory(
        UInteger  id,
        String    imageUrl,
        UInteger  locationId,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.imageUrl = imageUrl;
        this.locationId = locationId;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public String getImageUrl() {
        return this.imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public UInteger getLocationId() {
        return this.locationId;
    }

    public void setLocationId(UInteger locationId) {
        this.locationId = locationId;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        return "N\u00b0 " +id;
    }

    public void setProductCategoryLocalized(List<ProductCategoryLocalized> productCategoryLocalized) {
        this.productCategoryLocalized = productCategoryLocalized;
    }

    public List<ProductCategoryLocalized> getProductCategoryLocalized() {
        return productCategoryLocalized;
    }

    public ProductCategoryLocalized getProductCategoryTranslation(Language language) {
        return StreamSupport.stream(productCategoryLocalized)
                .filter(pcl -> pcl.getLanguageCode().equals(language.getCode()))
                .findFirst()
                .get();
    }
}
