/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.models.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Table implements Serializable {

    private static final long serialVersionUID = 648872574;

    private UInteger  id;
    private UShort    places;
    private Timestamp createdAt;
    private Timestamp updatedAt;

    public Table() {}

    public Table(Table value) {
        this.id = value.id;
        this.places = value.places;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public Table(
        UInteger  id,
        UShort    places,
        Timestamp createdAt,
        Timestamp updatedAt
    ) {
        this.id = id;
        this.places = places;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public UShort getPlaces() {
        return this.places;
    }

    public void setPlaces(UShort places) {
        this.places = places;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Table (");

        sb.append(id);
        sb.append(", ").append(places);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
