/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.server.database;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import org.jooq.types.UInteger;

import lu.btsi.bragi.ros.server.database.tables.Allergen;
import lu.btsi.bragi.ros.server.database.tables.Allergenlocalized;
import lu.btsi.bragi.ros.server.database.tables.Invoice;
import lu.btsi.bragi.ros.server.database.tables.Language;
import lu.btsi.bragi.ros.server.database.tables.Order;
import lu.btsi.bragi.ros.server.database.tables.Product;
import lu.btsi.bragi.ros.server.database.tables.Productallergen;
import lu.btsi.bragi.ros.server.database.tables.Productlocalized;
import lu.btsi.bragi.ros.server.database.tables.Productpricefororder;
import lu.btsi.bragi.ros.server.database.tables.Table;
import lu.btsi.bragi.ros.server.database.tables.Waiter;
import lu.btsi.bragi.ros.server.database.tables.records.AllergenRecord;
import lu.btsi.bragi.ros.server.database.tables.records.AllergenlocalizedRecord;
import lu.btsi.bragi.ros.server.database.tables.records.InvoiceRecord;
import lu.btsi.bragi.ros.server.database.tables.records.LanguageRecord;
import lu.btsi.bragi.ros.server.database.tables.records.OrderRecord;
import lu.btsi.bragi.ros.server.database.tables.records.ProductRecord;
import lu.btsi.bragi.ros.server.database.tables.records.ProductallergenRecord;
import lu.btsi.bragi.ros.server.database.tables.records.ProductlocalizedRecord;
import lu.btsi.bragi.ros.server.database.tables.records.ProductpricefororderRecord;
import lu.btsi.bragi.ros.server.database.tables.records.TableRecord;
import lu.btsi.bragi.ros.server.database.tables.records.WaiterRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>ros</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is database by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AllergenRecord, UInteger> IDENTITY_ALLERGEN = Identities0.IDENTITY_ALLERGEN;
    public static final Identity<InvoiceRecord, UInteger> IDENTITY_INVOICE = Identities0.IDENTITY_INVOICE;
    public static final Identity<OrderRecord, UInteger> IDENTITY_ORDER = Identities0.IDENTITY_ORDER;
    public static final Identity<ProductRecord, UInteger> IDENTITY_PRODUCT = Identities0.IDENTITY_PRODUCT;
    public static final Identity<TableRecord, UInteger> IDENTITY_TABLE = Identities0.IDENTITY_TABLE;
    public static final Identity<WaiterRecord, UInteger> IDENTITY_WAITER = Identities0.IDENTITY_WAITER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AllergenRecord> KEY_ALLERGEN_PRIMARY = UniqueKeys0.KEY_ALLERGEN_PRIMARY;
    public static final UniqueKey<AllergenlocalizedRecord> KEY_ALLERGENLOCALIZED_PRIMARY = UniqueKeys0.KEY_ALLERGENLOCALIZED_PRIMARY;
    public static final UniqueKey<InvoiceRecord> KEY_INVOICE_PRIMARY = UniqueKeys0.KEY_INVOICE_PRIMARY;
    public static final UniqueKey<LanguageRecord> KEY_LANGUAGE_PRIMARY = UniqueKeys0.KEY_LANGUAGE_PRIMARY;
    public static final UniqueKey<OrderRecord> KEY_ORDER_PRIMARY = UniqueKeys0.KEY_ORDER_PRIMARY;
    public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = UniqueKeys0.KEY_PRODUCT_PRIMARY;
    public static final UniqueKey<ProductallergenRecord> KEY_PRODUCTALLERGEN_PRIMARY = UniqueKeys0.KEY_PRODUCTALLERGEN_PRIMARY;
    public static final UniqueKey<ProductlocalizedRecord> KEY_PRODUCTLOCALIZED_PRIMARY = UniqueKeys0.KEY_PRODUCTLOCALIZED_PRIMARY;
    public static final UniqueKey<ProductpricefororderRecord> KEY_PRODUCTPRICEFORORDER_PRIMARY = UniqueKeys0.KEY_PRODUCTPRICEFORORDER_PRIMARY;
    public static final UniqueKey<TableRecord> KEY_TABLE_PRIMARY = UniqueKeys0.KEY_TABLE_PRIMARY;
    public static final UniqueKey<WaiterRecord> KEY_WAITER_PRIMARY = UniqueKeys0.KEY_WAITER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<AllergenlocalizedRecord, AllergenRecord> FK_ALLERGENLOCALIZED_ALLERGEN = ForeignKeys0.FK_ALLERGENLOCALIZED_ALLERGEN;
    public static final ForeignKey<AllergenlocalizedRecord, LanguageRecord> FK_ALLERGENLOCALIZED_LANGUAGE = ForeignKeys0.FK_ALLERGENLOCALIZED_LANGUAGE;
    public static final ForeignKey<OrderRecord, TableRecord> FK_ORDER_TABLE = ForeignKeys0.FK_ORDER_TABLE;
    public static final ForeignKey<OrderRecord, WaiterRecord> FK_ORDER_WAITER = ForeignKeys0.FK_ORDER_WAITER;
    public static final ForeignKey<OrderRecord, InvoiceRecord> FK_ORDER_INVOICE = ForeignKeys0.FK_ORDER_INVOICE;
    public static final ForeignKey<ProductallergenRecord, AllergenRecord> FK_PRODUCTALLERGEN_ALLERGEN = ForeignKeys0.FK_PRODUCTALLERGEN_ALLERGEN;
    public static final ForeignKey<ProductallergenRecord, ProductRecord> FK_PRODUCTALLERGEN_PRODUCT = ForeignKeys0.FK_PRODUCTALLERGEN_PRODUCT;
    public static final ForeignKey<ProductlocalizedRecord, ProductRecord> FK_PRODUCTLOCALIZED_PRODUCT = ForeignKeys0.FK_PRODUCTLOCALIZED_PRODUCT;
    public static final ForeignKey<ProductlocalizedRecord, LanguageRecord> FK_PRODUCTLOCALIZED_LANGUAGE = ForeignKeys0.FK_PRODUCTLOCALIZED_LANGUAGE;
    public static final ForeignKey<ProductpricefororderRecord, ProductRecord> FK_PRODUCTPRICEFORORDER_PRODUCT = ForeignKeys0.FK_PRODUCTPRICEFORORDER_PRODUCT;
    public static final ForeignKey<ProductpricefororderRecord, OrderRecord> FK_PRODUCTPRICEFORORDER_ORDER = ForeignKeys0.FK_PRODUCTPRICEFORORDER_ORDER;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<AllergenRecord, UInteger> IDENTITY_ALLERGEN = createIdentity(Allergen.ALLERGEN, Allergen.ALLERGEN.ID);
        public static Identity<InvoiceRecord, UInteger> IDENTITY_INVOICE = createIdentity(Invoice.INVOICE, Invoice.INVOICE.ID);
        public static Identity<OrderRecord, UInteger> IDENTITY_ORDER = createIdentity(Order.ORDER, Order.ORDER.ID);
        public static Identity<ProductRecord, UInteger> IDENTITY_PRODUCT = createIdentity(Product.PRODUCT, Product.PRODUCT.ID);
        public static Identity<TableRecord, UInteger> IDENTITY_TABLE = createIdentity(Table.TABLE, Table.TABLE.ID);
        public static Identity<WaiterRecord, UInteger> IDENTITY_WAITER = createIdentity(Waiter.WAITER, Waiter.WAITER.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AllergenRecord> KEY_ALLERGEN_PRIMARY = createUniqueKey(Allergen.ALLERGEN, "KEY_Allergen_PRIMARY", Allergen.ALLERGEN.ID);
        public static final UniqueKey<AllergenlocalizedRecord> KEY_ALLERGENLOCALIZED_PRIMARY = createUniqueKey(Allergenlocalized.ALLERGENLOCALIZED, "KEY_AllergenLocalized_PRIMARY", Allergenlocalized.ALLERGENLOCALIZED.ALLERGEN_ID, Allergenlocalized.ALLERGENLOCALIZED.LANGUAGE_CODE);
        public static final UniqueKey<InvoiceRecord> KEY_INVOICE_PRIMARY = createUniqueKey(Invoice.INVOICE, "KEY_Invoice_PRIMARY", Invoice.INVOICE.ID);
        public static final UniqueKey<LanguageRecord> KEY_LANGUAGE_PRIMARY = createUniqueKey(Language.LANGUAGE, "KEY_Language_PRIMARY", Language.LANGUAGE.CODE);
        public static final UniqueKey<OrderRecord> KEY_ORDER_PRIMARY = createUniqueKey(Order.ORDER, "KEY_Order_PRIMARY", Order.ORDER.ID);
        public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = createUniqueKey(Product.PRODUCT, "KEY_Product_PRIMARY", Product.PRODUCT.ID);
        public static final UniqueKey<ProductallergenRecord> KEY_PRODUCTALLERGEN_PRIMARY = createUniqueKey(Productallergen.PRODUCTALLERGEN, "KEY_ProductAllergen_PRIMARY", Productallergen.PRODUCTALLERGEN.ALLERGEN_ID, Productallergen.PRODUCTALLERGEN.PRODUCT_ID);
        public static final UniqueKey<ProductlocalizedRecord> KEY_PRODUCTLOCALIZED_PRIMARY = createUniqueKey(Productlocalized.PRODUCTLOCALIZED, "KEY_ProductLocalized_PRIMARY", Productlocalized.PRODUCTLOCALIZED.PRODUCT_ID, Productlocalized.PRODUCTLOCALIZED.LANGUAGE_CODE);
        public static final UniqueKey<ProductpricefororderRecord> KEY_PRODUCTPRICEFORORDER_PRIMARY = createUniqueKey(Productpricefororder.PRODUCTPRICEFORORDER, "KEY_ProductPriceForOrder_PRIMARY", Productpricefororder.PRODUCTPRICEFORORDER.PRODUCT_ID, Productpricefororder.PRODUCTPRICEFORORDER.ORDER_ID);
        public static final UniqueKey<TableRecord> KEY_TABLE_PRIMARY = createUniqueKey(Table.TABLE, "KEY_Table_PRIMARY", Table.TABLE.ID);
        public static final UniqueKey<WaiterRecord> KEY_WAITER_PRIMARY = createUniqueKey(Waiter.WAITER, "KEY_Waiter_PRIMARY", Waiter.WAITER.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<AllergenlocalizedRecord, AllergenRecord> FK_ALLERGENLOCALIZED_ALLERGEN = createForeignKey(Keys.KEY_ALLERGEN_PRIMARY, Allergenlocalized.ALLERGENLOCALIZED, "fk_AllergenLocalized_Allergen", Allergenlocalized.ALLERGENLOCALIZED.ALLERGEN_ID);
        public static final ForeignKey<AllergenlocalizedRecord, LanguageRecord> FK_ALLERGENLOCALIZED_LANGUAGE = createForeignKey(Keys.KEY_LANGUAGE_PRIMARY, Allergenlocalized.ALLERGENLOCALIZED, "fk_AllergenLocalized_Language", Allergenlocalized.ALLERGENLOCALIZED.LANGUAGE_CODE);
        public static final ForeignKey<OrderRecord, TableRecord> FK_ORDER_TABLE = createForeignKey(Keys.KEY_TABLE_PRIMARY, Order.ORDER, "fk_Order_Table", Order.ORDER.TABLE_ID);
        public static final ForeignKey<OrderRecord, WaiterRecord> FK_ORDER_WAITER = createForeignKey(Keys.KEY_WAITER_PRIMARY, Order.ORDER, "fk_Order_Waiter", Order.ORDER.WAITER_ID);
        public static final ForeignKey<OrderRecord, InvoiceRecord> FK_ORDER_INVOICE = createForeignKey(Keys.KEY_INVOICE_PRIMARY, Order.ORDER, "fk_Order_Invoice", Order.ORDER.INVOICE_ID);
        public static final ForeignKey<ProductallergenRecord, AllergenRecord> FK_PRODUCTALLERGEN_ALLERGEN = createForeignKey(Keys.KEY_ALLERGEN_PRIMARY, Productallergen.PRODUCTALLERGEN, "fk_ProductAllergen_Allergen", Productallergen.PRODUCTALLERGEN.ALLERGEN_ID);
        public static final ForeignKey<ProductallergenRecord, ProductRecord> FK_PRODUCTALLERGEN_PRODUCT = createForeignKey(Keys.KEY_PRODUCT_PRIMARY, Productallergen.PRODUCTALLERGEN, "fk_ProductAllergen_Product", Productallergen.PRODUCTALLERGEN.PRODUCT_ID);
        public static final ForeignKey<ProductlocalizedRecord, ProductRecord> FK_PRODUCTLOCALIZED_PRODUCT = createForeignKey(Keys.KEY_PRODUCT_PRIMARY, Productlocalized.PRODUCTLOCALIZED, "fk_ProductLocalized_Product", Productlocalized.PRODUCTLOCALIZED.PRODUCT_ID);
        public static final ForeignKey<ProductlocalizedRecord, LanguageRecord> FK_PRODUCTLOCALIZED_LANGUAGE = createForeignKey(Keys.KEY_LANGUAGE_PRIMARY, Productlocalized.PRODUCTLOCALIZED, "fk_ProductLocalized_Language", Productlocalized.PRODUCTLOCALIZED.LANGUAGE_CODE);
        public static final ForeignKey<ProductpricefororderRecord, ProductRecord> FK_PRODUCTPRICEFORORDER_PRODUCT = createForeignKey(Keys.KEY_PRODUCT_PRIMARY, Productpricefororder.PRODUCTPRICEFORORDER, "fk_ProductPriceForOrder_Product", Productpricefororder.PRODUCTPRICEFORORDER.PRODUCT_ID);
        public static final ForeignKey<ProductpricefororderRecord, OrderRecord> FK_PRODUCTPRICEFORORDER_ORDER = createForeignKey(Keys.KEY_ORDER_PRIMARY, Productpricefororder.PRODUCTPRICEFORORDER, "fk_ProductPriceForOrder_Order", Productpricefororder.PRODUCTPRICEFORORDER.ORDER_ID);
    }
}
