/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.server.database;


import lu.btsi.bragi.ros.server.database.tables.*;
import org.jooq.Catalog;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ros extends SchemaImpl {

    private static final long serialVersionUID = 999865326;

    /**
     * The reference instance of <code>ros</code>
     */
    public static final Ros ROS = new Ros();

    /**
     * The table <code>ros.Allergen</code>.
     */
    public final Allergen ALLERGEN = lu.btsi.bragi.ros.server.database.tables.Allergen.ALLERGEN;

    /**
     * The table <code>ros.Allergen_Localized</code>.
     */
    public final AllergenLocalized ALLERGEN_LOCALIZED = lu.btsi.bragi.ros.server.database.tables.AllergenLocalized.ALLERGEN_LOCALIZED;

    /**
     * The table <code>ros.Invoice</code>.
     */
    public final Invoice INVOICE = lu.btsi.bragi.ros.server.database.tables.Invoice.INVOICE;

    /**
     * The table <code>ros.Language</code>.
     */
    public final Language LANGUAGE = lu.btsi.bragi.ros.server.database.tables.Language.LANGUAGE;

    /**
     * The table <code>ros.Location</code>.
     */
    public final Location LOCATION = lu.btsi.bragi.ros.server.database.tables.Location.LOCATION;

    /**
     * The table <code>ros.Order</code>.
     */
    public final Order ORDER = lu.btsi.bragi.ros.server.database.tables.Order.ORDER;

    /**
     * The table <code>ros.Product</code>.
     */
    public final Product PRODUCT = lu.btsi.bragi.ros.server.database.tables.Product.PRODUCT;

    /**
     * The table <code>ros.Product_Allergen</code>.
     */
    public final ProductAllergen PRODUCT_ALLERGEN = lu.btsi.bragi.ros.server.database.tables.ProductAllergen.PRODUCT_ALLERGEN;

    /**
     * The table <code>ros.Product_Category</code>.
     */
    public final ProductCategory PRODUCT_CATEGORY = lu.btsi.bragi.ros.server.database.tables.ProductCategory.PRODUCT_CATEGORY;

    /**
     * The table <code>ros.Product_Category_Localized</code>.
     */
    public final ProductCategoryLocalized PRODUCT_CATEGORY_LOCALIZED = lu.btsi.bragi.ros.server.database.tables.ProductCategoryLocalized.PRODUCT_CATEGORY_LOCALIZED;

    /**
     * The table <code>ros.Product_Localized</code>.
     */
    public final ProductLocalized PRODUCT_LOCALIZED = lu.btsi.bragi.ros.server.database.tables.ProductLocalized.PRODUCT_LOCALIZED;

    /**
     * The table <code>ros.Product_Price_For_Order</code>.
     */
    public final ProductPriceForOrder PRODUCT_PRICE_FOR_ORDER = lu.btsi.bragi.ros.server.database.tables.ProductPriceForOrder.PRODUCT_PRICE_FOR_ORDER;

    /**
     * The table <code>ros.Table</code>.
     */
    public final Table TABLE = lu.btsi.bragi.ros.server.database.tables.Table.TABLE;

    /**
     * The table <code>ros.Waiter</code>.
     */
    public final Waiter WAITER = lu.btsi.bragi.ros.server.database.tables.Waiter.WAITER;

    /**
     * No further instances allowed
     */
    private Ros() {
        super("ros", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<org.jooq.Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<org.jooq.Table<?>> getTables0() {
        return Arrays.<org.jooq.Table<?>>asList(
            Allergen.ALLERGEN,
            AllergenLocalized.ALLERGEN_LOCALIZED,
            Invoice.INVOICE,
            Language.LANGUAGE,
            Location.LOCATION,
            Order.ORDER,
            Product.PRODUCT,
            ProductAllergen.PRODUCT_ALLERGEN,
            ProductCategory.PRODUCT_CATEGORY,
            ProductCategoryLocalized.PRODUCT_CATEGORY_LOCALIZED,
            ProductLocalized.PRODUCT_LOCALIZED,
            ProductPriceForOrder.PRODUCT_PRICE_FOR_ORDER,
            Table.TABLE,
            Waiter.WAITER);
    }
}
