/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.server.database;


import javax.annotation.Generated;

import lu.btsi.bragi.ros.server.database.tables.Allergen;
import lu.btsi.bragi.ros.server.database.tables.AllergenLocalized;
import lu.btsi.bragi.ros.server.database.tables.Invoice;
import lu.btsi.bragi.ros.server.database.tables.Language;
import lu.btsi.bragi.ros.server.database.tables.Order;
import lu.btsi.bragi.ros.server.database.tables.Product;
import lu.btsi.bragi.ros.server.database.tables.ProductAllergen;
import lu.btsi.bragi.ros.server.database.tables.ProductCategory;
import lu.btsi.bragi.ros.server.database.tables.ProductCategoryLocalized;
import lu.btsi.bragi.ros.server.database.tables.ProductLocalized;
import lu.btsi.bragi.ros.server.database.tables.ProductPriceForOrder;
import lu.btsi.bragi.ros.server.database.tables.Table;
import lu.btsi.bragi.ros.server.database.tables.Waiter;


/**
 * Convenience access to all tables in ros
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ros.Allergen</code>.
     */
    public static final Allergen ALLERGEN = lu.btsi.bragi.ros.server.database.tables.Allergen.ALLERGEN;

    /**
     * The table <code>ros.Allergen_Localized</code>.
     */
    public static final AllergenLocalized ALLERGEN_LOCALIZED = lu.btsi.bragi.ros.server.database.tables.AllergenLocalized.ALLERGEN_LOCALIZED;

    /**
     * The table <code>ros.Invoice</code>.
     */
    public static final Invoice INVOICE = lu.btsi.bragi.ros.server.database.tables.Invoice.INVOICE;

    /**
     * The table <code>ros.Language</code>.
     */
    public static final Language LANGUAGE = lu.btsi.bragi.ros.server.database.tables.Language.LANGUAGE;

    /**
     * The table <code>ros.Order</code>.
     */
    public static final Order ORDER = lu.btsi.bragi.ros.server.database.tables.Order.ORDER;

    /**
     * The table <code>ros.Product</code>.
     */
    public static final Product PRODUCT = lu.btsi.bragi.ros.server.database.tables.Product.PRODUCT;

    /**
     * The table <code>ros.Product_Allergen</code>.
     */
    public static final ProductAllergen PRODUCT_ALLERGEN = lu.btsi.bragi.ros.server.database.tables.ProductAllergen.PRODUCT_ALLERGEN;

    /**
     * The table <code>ros.Product_Category</code>.
     */
    public static final ProductCategory PRODUCT_CATEGORY = lu.btsi.bragi.ros.server.database.tables.ProductCategory.PRODUCT_CATEGORY;

    /**
     * The table <code>ros.Product_Category_Localized</code>.
     */
    public static final ProductCategoryLocalized PRODUCT_CATEGORY_LOCALIZED = lu.btsi.bragi.ros.server.database.tables.ProductCategoryLocalized.PRODUCT_CATEGORY_LOCALIZED;

    /**
     * The table <code>ros.Product_Localized</code>.
     */
    public static final ProductLocalized PRODUCT_LOCALIZED = lu.btsi.bragi.ros.server.database.tables.ProductLocalized.PRODUCT_LOCALIZED;

    /**
     * The table <code>ros.Product_Price_For_Order</code>.
     */
    public static final ProductPriceForOrder PRODUCT_PRICE_FOR_ORDER = lu.btsi.bragi.ros.server.database.tables.ProductPriceForOrder.PRODUCT_PRICE_FOR_ORDER;

    /**
     * The table <code>ros.Table</code>.
     */
    public static final Table TABLE = lu.btsi.bragi.ros.server.database.tables.Table.TABLE;

    /**
     * The table <code>ros.Waiter</code>.
     */
    public static final Waiter WAITER = lu.btsi.bragi.ros.server.database.tables.Waiter.WAITER;
}
