/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.server.database.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import lu.btsi.bragi.ros.server.database.Keys;
import lu.btsi.bragi.ros.server.database.Ros;
import lu.btsi.bragi.ros.server.database.tables.records.AllergenRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Allergen extends TableImpl<AllergenRecord> {

    private static final long serialVersionUID = -1330635812;

    /**
     * The reference instance of <code>ros.Allergen</code>
     */
    public static final Allergen ALLERGEN = new Allergen();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AllergenRecord> getRecordType() {
        return AllergenRecord.class;
    }

    /**
     * The column <code>ros.Allergen.id</code>.
     */
    public final TableField<AllergenRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>ros.Allergen.created_at</code>.
     */
    public final TableField<AllergenRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ros.Allergen.updated_at</code>.
     */
    public final TableField<AllergenRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ros.Allergen</code> table reference
     */
    public Allergen() {
        this("Allergen", null);
    }

    /**
     * Create an aliased <code>ros.Allergen</code> table reference
     */
    public Allergen(String alias) {
        this(alias, ALLERGEN);
    }

    private Allergen(String alias, Table<AllergenRecord> aliased) {
        this(alias, aliased, null);
    }

    private Allergen(String alias, Table<AllergenRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ros.ROS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AllergenRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_ALLERGEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AllergenRecord> getPrimaryKey() {
        return Keys.KEY_ALLERGEN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AllergenRecord>> getKeys() {
        return Arrays.<UniqueKey<AllergenRecord>>asList(Keys.KEY_ALLERGEN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Allergen as(String alias) {
        return new Allergen(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Allergen rename(String name) {
        return new Allergen(name, null);
    }
}
