/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.server.database.tables;


import lu.btsi.bragi.ros.server.database.Keys;
import lu.btsi.bragi.ros.server.database.Ros;
import lu.btsi.bragi.ros.server.database.tables.records.ProductCategoryLocalizedRecord;
import org.jooq.*;
import org.jooq.Table;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategoryLocalized extends TableImpl<ProductCategoryLocalizedRecord> {

    private static final long serialVersionUID = 1360559590;

    /**
     * The reference instance of <code>ros.Product_Category_Localized</code>
     */
    public static final ProductCategoryLocalized PRODUCT_CATEGORY_LOCALIZED = new ProductCategoryLocalized();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductCategoryLocalizedRecord> getRecordType() {
        return ProductCategoryLocalizedRecord.class;
    }

    /**
     * The column <code>ros.Product_Category_Localized.product_category_id</code>.
     */
    public final TableField<ProductCategoryLocalizedRecord, UInteger> PRODUCT_CATEGORY_ID = createField("product_category_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>ros.Product_Category_Localized.language_code</code>.
     */
    public final TableField<ProductCategoryLocalizedRecord, String> LANGUAGE_CODE = createField("language_code", org.jooq.impl.SQLDataType.CHAR.length(2).nullable(false), this, "");

    /**
     * The column <code>ros.Product_Category_Localized.label</code>.
     */
    public final TableField<ProductCategoryLocalizedRecord, String> LABEL = createField("label", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>ros.Product_Category_Localized.created_at</code>.
     */
    public final TableField<ProductCategoryLocalizedRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ros.Product_Category_Localized.updated_at</code>.
     */
    public final TableField<ProductCategoryLocalizedRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ros.Product_Category_Localized</code> table reference
     */
    public ProductCategoryLocalized() {
        this("Product_Category_Localized", null);
    }

    /**
     * Create an aliased <code>ros.Product_Category_Localized</code> table reference
     */
    public ProductCategoryLocalized(String alias) {
        this(alias, PRODUCT_CATEGORY_LOCALIZED);
    }

    private ProductCategoryLocalized(String alias, Table<ProductCategoryLocalizedRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProductCategoryLocalized(String alias, Table<ProductCategoryLocalizedRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ros.ROS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProductCategoryLocalizedRecord> getPrimaryKey() {
        return Keys.KEY_PRODUCT_CATEGORY_LOCALIZED_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProductCategoryLocalizedRecord>> getKeys() {
        return Arrays.<UniqueKey<ProductCategoryLocalizedRecord>>asList(Keys.KEY_PRODUCT_CATEGORY_LOCALIZED_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ProductCategoryLocalizedRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProductCategoryLocalizedRecord, ?>>asList(Keys.FK_PRODUCTCATEGORYLOCALIZED_PRODUCTCATEGORY, Keys.FK_PRODUCTCATEGORYLOCALIZED_LANGUAGE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCategoryLocalized as(String alias) {
        return new ProductCategoryLocalized(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductCategoryLocalized rename(String name) {
        return new ProductCategoryLocalized(name, null);
    }
}
