/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.server.database.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import lu.btsi.bragi.ros.server.database.Keys;
import lu.btsi.bragi.ros.server.database.Ros;
import lu.btsi.bragi.ros.server.database.tables.records.ProductCategoryRecord;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategory extends TableImpl<ProductCategoryRecord> {

    private static final long serialVersionUID = -1634616588;

    /**
     * The reference instance of <code>ros.Product_Category</code>
     */
    public static final ProductCategory PRODUCT_CATEGORY = new ProductCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductCategoryRecord> getRecordType() {
        return ProductCategoryRecord.class;
    }

    /**
     * The column <code>ros.Product_Category.id</code>.
     */
    public final TableField<ProductCategoryRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>ros.Product_Category.image_url</code>.
     */
    public final TableField<ProductCategoryRecord, String> IMAGE_URL = createField("image_url", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

    /**
     * Create a <code>ros.Product_Category</code> table reference
     */
    public ProductCategory() {
        this("Product_Category", null);
    }

    /**
     * Create an aliased <code>ros.Product_Category</code> table reference
     */
    public ProductCategory(String alias) {
        this(alias, PRODUCT_CATEGORY);
    }

    private ProductCategory(String alias, Table<ProductCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProductCategory(String alias, Table<ProductCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ros.ROS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProductCategoryRecord> getPrimaryKey() {
        return Keys.KEY_PRODUCT_CATEGORY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProductCategoryRecord>> getKeys() {
        return Arrays.<UniqueKey<ProductCategoryRecord>>asList(Keys.KEY_PRODUCT_CATEGORY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCategory as(String alias) {
        return new ProductCategory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductCategory rename(String name) {
        return new ProductCategory(name, null);
    }
}
