/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.server.database.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import lu.btsi.bragi.ros.server.database.Keys;
import lu.btsi.bragi.ros.server.database.Ros;
import lu.btsi.bragi.ros.server.database.tables.records.ProductLocalizedRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductLocalized extends TableImpl<ProductLocalizedRecord> {

    private static final long serialVersionUID = 699612810;

    /**
     * The reference instance of <code>ros.Product_Localized</code>
     */
    public static final ProductLocalized PRODUCT_LOCALIZED = new ProductLocalized();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductLocalizedRecord> getRecordType() {
        return ProductLocalizedRecord.class;
    }

    /**
     * The column <code>ros.Product_Localized.product_id</code>.
     */
    public final TableField<ProductLocalizedRecord, UInteger> PRODUCT_ID = createField("product_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>ros.Product_Localized.language_code</code>.
     */
    public final TableField<ProductLocalizedRecord, String> LANGUAGE_CODE = createField("language_code", org.jooq.impl.SQLDataType.CHAR.length(2).nullable(false), this, "");

    /**
     * The column <code>ros.Product_Localized.label</code>.
     */
    public final TableField<ProductLocalizedRecord, String> LABEL = createField("label", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>ros.Product_Localized.created_at</code>.
     */
    public final TableField<ProductLocalizedRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ros.Product_Localized.updated_at</code>.
     */
    public final TableField<ProductLocalizedRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ros.Product_Localized</code> table reference
     */
    public ProductLocalized() {
        this("Product_Localized", null);
    }

    /**
     * Create an aliased <code>ros.Product_Localized</code> table reference
     */
    public ProductLocalized(String alias) {
        this(alias, PRODUCT_LOCALIZED);
    }

    private ProductLocalized(String alias, Table<ProductLocalizedRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProductLocalized(String alias, Table<ProductLocalizedRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ros.ROS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProductLocalizedRecord> getPrimaryKey() {
        return Keys.KEY_PRODUCT_LOCALIZED_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProductLocalizedRecord>> getKeys() {
        return Arrays.<UniqueKey<ProductLocalizedRecord>>asList(Keys.KEY_PRODUCT_LOCALIZED_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ProductLocalizedRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProductLocalizedRecord, ?>>asList(Keys.FK_PRODUCTLOCALIZED_PRODUCT, Keys.FK_PRODUCTLOCALIZED_LANGUAGE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductLocalized as(String alias) {
        return new ProductLocalized(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductLocalized rename(String name) {
        return new ProductLocalized(name, null);
    }
}
