/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.server.database.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import lu.btsi.bragi.ros.server.database.Keys;
import lu.btsi.bragi.ros.server.database.Ros;
import lu.btsi.bragi.ros.server.database.tables.records.WaiterRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Waiter extends TableImpl<WaiterRecord> {

    private static final long serialVersionUID = -1278140927;

    /**
     * The reference instance of <code>ros.Waiter</code>
     */
    public static final Waiter WAITER = new Waiter();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<WaiterRecord> getRecordType() {
        return WaiterRecord.class;
    }

    /**
     * The column <code>ros.Waiter.id</code>.
     */
    public final TableField<WaiterRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>ros.Waiter.name</code>.
     */
    public final TableField<WaiterRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>ros.Waiter.created_at</code>.
     */
    public final TableField<WaiterRecord, Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>ros.Waiter.updated_at</code>.
     */
    public final TableField<WaiterRecord, Timestamp> UPDATED_AT = createField("updated_at", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ros.Waiter</code> table reference
     */
    public Waiter() {
        this("Waiter", null);
    }

    /**
     * Create an aliased <code>ros.Waiter</code> table reference
     */
    public Waiter(String alias) {
        this(alias, WAITER);
    }

    private Waiter(String alias, Table<WaiterRecord> aliased) {
        this(alias, aliased, null);
    }

    private Waiter(String alias, Table<WaiterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Ros.ROS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<WaiterRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_WAITER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<WaiterRecord> getPrimaryKey() {
        return Keys.KEY_WAITER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<WaiterRecord>> getKeys() {
        return Arrays.<UniqueKey<WaiterRecord>>asList(Keys.KEY_WAITER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Waiter as(String alias) {
        return new Waiter(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Waiter rename(String name) {
        return new Waiter(name, null);
    }
}
