/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.server.database.tables.records;


import javax.annotation.Generated;

import lu.btsi.bragi.ros.server.database.tables.AllergenLocalized;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AllergenLocalizedRecord extends UpdatableRecordImpl<AllergenLocalizedRecord> implements Record2<UInteger, String> {

    private static final long serialVersionUID = -277145967;

    /**
     * Setter for <code>ros.Allergen_Localized.allergen_id</code>.
     */
    public void setAllergenId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>ros.Allergen_Localized.allergen_id</code>.
     */
    public UInteger getAllergenId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>ros.Allergen_Localized.language_code</code>.
     */
    public void setLanguageCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ros.Allergen_Localized.language_code</code>.
     */
    public String getLanguageCode() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UInteger, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UInteger, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return AllergenLocalized.ALLERGEN_LOCALIZED.ALLERGEN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AllergenLocalized.ALLERGEN_LOCALIZED.LANGUAGE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getAllergenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLanguageCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllergenLocalizedRecord value1(UInteger value) {
        setAllergenId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllergenLocalizedRecord value2(String value) {
        setLanguageCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AllergenLocalizedRecord values(UInteger value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AllergenLocalizedRecord
     */
    public AllergenLocalizedRecord() {
        super(AllergenLocalized.ALLERGEN_LOCALIZED);
    }

    /**
     * Create a detached, initialised AllergenLocalizedRecord
     */
    public AllergenLocalizedRecord(UInteger allergenId, String languageCode) {
        super(AllergenLocalized.ALLERGEN_LOCALIZED);

        set(0, allergenId);
        set(1, languageCode);
    }
}
