/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.server.database.tables.records;


import javax.annotation.Generated;

import lu.btsi.bragi.ros.server.database.tables.ProductCategoryLocalized;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategoryLocalizedRecord extends UpdatableRecordImpl<ProductCategoryLocalizedRecord> implements Record3<UInteger, String, String> {

    private static final long serialVersionUID = 646644572;

    /**
     * Setter for <code>ros.Product_Category_Localized.product_category_id</code>.
     */
    public void setProductCategoryId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>ros.Product_Category_Localized.product_category_id</code>.
     */
    public UInteger getProductCategoryId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>ros.Product_Category_Localized.language_code</code>.
     */
    public void setLanguageCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ros.Product_Category_Localized.language_code</code>.
     */
    public String getLanguageCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ros.Product_Category_Localized.label</code>.
     */
    public void setLabel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ros.Product_Category_Localized.label</code>.
     */
    public String getLabel() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UInteger, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return ProductCategoryLocalized.PRODUCT_CATEGORY_LOCALIZED.PRODUCT_CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProductCategoryLocalized.PRODUCT_CATEGORY_LOCALIZED.LANGUAGE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ProductCategoryLocalized.PRODUCT_CATEGORY_LOCALIZED.LABEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getProductCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLanguageCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCategoryLocalizedRecord value1(UInteger value) {
        setProductCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCategoryLocalizedRecord value2(String value) {
        setLanguageCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCategoryLocalizedRecord value3(String value) {
        setLabel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCategoryLocalizedRecord values(UInteger value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductCategoryLocalizedRecord
     */
    public ProductCategoryLocalizedRecord() {
        super(ProductCategoryLocalized.PRODUCT_CATEGORY_LOCALIZED);
    }

    /**
     * Create a detached, initialised ProductCategoryLocalizedRecord
     */
    public ProductCategoryLocalizedRecord(UInteger productCategoryId, String languageCode, String label) {
        super(ProductCategoryLocalized.PRODUCT_CATEGORY_LOCALIZED);

        set(0, productCategoryId);
        set(1, languageCode);
        set(2, label);
    }
}
