/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.server.database.tables.records;


import lu.btsi.bragi.ros.server.database.tables.ProductCategoryLocalized;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductCategoryLocalizedRecord extends UpdatableRecordImpl<ProductCategoryLocalizedRecord> implements Record5<UInteger, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1252420154;

    /**
     * Setter for <code>ros.Product_Category_Localized.product_category_id</code>.
     */
    public void setProductCategoryId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>ros.Product_Category_Localized.product_category_id</code>.
     */
    public UInteger getProductCategoryId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>ros.Product_Category_Localized.language_code</code>.
     */
    public void setLanguageCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ros.Product_Category_Localized.language_code</code>.
     */
    public String getLanguageCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ros.Product_Category_Localized.label</code>.
     */
    public void setLabel(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ros.Product_Category_Localized.label</code>.
     */
    public String getLabel() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ros.Product_Category_Localized.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>ros.Product_Category_Localized.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>ros.Product_Category_Localized.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>ros.Product_Category_Localized.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UInteger, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return ProductCategoryLocalized.PRODUCT_CATEGORY_LOCALIZED.PRODUCT_CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ProductCategoryLocalized.PRODUCT_CATEGORY_LOCALIZED.LANGUAGE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ProductCategoryLocalized.PRODUCT_CATEGORY_LOCALIZED.LABEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return ProductCategoryLocalized.PRODUCT_CATEGORY_LOCALIZED.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return ProductCategoryLocalized.PRODUCT_CATEGORY_LOCALIZED.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getProductCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getLanguageCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCategoryLocalizedRecord value1(UInteger value) {
        setProductCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCategoryLocalizedRecord value2(String value) {
        setLanguageCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCategoryLocalizedRecord value3(String value) {
        setLabel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCategoryLocalizedRecord value4(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCategoryLocalizedRecord value5(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductCategoryLocalizedRecord values(UInteger value1, String value2, String value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductCategoryLocalizedRecord
     */
    public ProductCategoryLocalizedRecord() {
        super(ProductCategoryLocalized.PRODUCT_CATEGORY_LOCALIZED);
    }

    /**
     * Create a detached, initialised ProductCategoryLocalizedRecord
     */
    public ProductCategoryLocalizedRecord(UInteger productCategoryId, String languageCode, String label, Timestamp createdAt, Timestamp updatedAt) {
        super(ProductCategoryLocalized.PRODUCT_CATEGORY_LOCALIZED);

        set(0, productCategoryId);
        set(1, languageCode);
        set(2, label);
        set(3, createdAt);
        set(4, updatedAt);
    }
}
