/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.server.database.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;

import lu.btsi.bragi.ros.server.database.tables.Productallergen;


/**
 * This class is database by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is database by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductallergenRecord extends UpdatableRecordImpl<ProductallergenRecord> implements Record4<UInteger, UInteger, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1224587408;

    /**
     * Setter for <code>ros.ProductAllergen.allergen_id</code>.
     */
    public void setAllergenId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>ros.ProductAllergen.allergen_id</code>.
     */
    public UInteger getAllergenId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>ros.ProductAllergen.product_id</code>.
     */
    public void setProductId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>ros.ProductAllergen.product_id</code>.
     */
    public UInteger getProductId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>ros.ProductAllergen.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>ros.ProductAllergen.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>ros.ProductAllergen.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>ros.ProductAllergen.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, UInteger> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, UInteger, Timestamp, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, UInteger, Timestamp, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return Productallergen.PRODUCTALLERGEN.ALLERGEN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return Productallergen.PRODUCTALLERGEN.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Productallergen.PRODUCTALLERGEN.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Productallergen.PRODUCTALLERGEN.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getAllergenId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductallergenRecord value1(UInteger value) {
        setAllergenId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductallergenRecord value2(UInteger value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductallergenRecord value3(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductallergenRecord value4(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductallergenRecord values(UInteger value1, UInteger value2, Timestamp value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductallergenRecord
     */
    public ProductallergenRecord() {
        super(Productallergen.PRODUCTALLERGEN);
    }

    /**
     * Create a detached, initialised ProductallergenRecord
     */
    public ProductallergenRecord(UInteger allergenId, UInteger productId, Timestamp createdAt, Timestamp updatedAt) {
        super(Productallergen.PRODUCTALLERGEN);

        set(0, allergenId);
        set(1, productId);
        set(2, createdAt);
        set(3, updatedAt);
    }
}
