/*
 * This file is generated by jOOQ.
*/
package lu.btsi.bragi.ros.server.database.tables.records;


import lu.btsi.bragi.ros.server.database.tables.ProductPriceForOrder;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductPriceForOrderRecord extends UpdatableRecordImpl<ProductPriceForOrderRecord> implements Record6<UInteger, UInteger, Double, UInteger, Timestamp, Timestamp> {

    private static final long serialVersionUID = -814266329;

    /**
     * Setter for <code>ros.Product_Price_For_Order.product_id</code>.
     */
    public void setProductId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>ros.Product_Price_For_Order.product_id</code>.
     */
    public UInteger getProductId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>ros.Product_Price_For_Order.order_id</code>.
     */
    public void setOrderId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>ros.Product_Price_For_Order.order_id</code>.
     */
    public UInteger getOrderId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>ros.Product_Price_For_Order.price_per_product</code>.
     */
    public void setPricePerProduct(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>ros.Product_Price_For_Order.price_per_product</code>.
     */
    public Double getPricePerProduct() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>ros.Product_Price_For_Order.quantity</code>.
     */
    public void setQuantity(UInteger value) {
        set(3, value);
    }

    /**
     * Getter for <code>ros.Product_Price_For_Order.quantity</code>.
     */
    public UInteger getQuantity() {
        return (UInteger) get(3);
    }

    /**
     * Setter for <code>ros.Product_Price_For_Order.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>ros.Product_Price_For_Order.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>ros.Product_Price_For_Order.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>ros.Product_Price_For_Order.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UInteger, UInteger> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, Double, UInteger, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<UInteger, UInteger, Double, UInteger, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return ProductPriceForOrder.PRODUCT_PRICE_FOR_ORDER.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return ProductPriceForOrder.PRODUCT_PRICE_FOR_ORDER.ORDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return ProductPriceForOrder.PRODUCT_PRICE_FOR_ORDER.PRICE_PER_PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field4() {
        return ProductPriceForOrder.PRODUCT_PRICE_FOR_ORDER.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return ProductPriceForOrder.PRODUCT_PRICE_FOR_ORDER.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return ProductPriceForOrder.PRODUCT_PRICE_FOR_ORDER.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getPricePerProduct();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value4() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductPriceForOrderRecord value1(UInteger value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductPriceForOrderRecord value2(UInteger value) {
        setOrderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductPriceForOrderRecord value3(Double value) {
        setPricePerProduct(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductPriceForOrderRecord value4(UInteger value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductPriceForOrderRecord value5(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductPriceForOrderRecord value6(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductPriceForOrderRecord values(UInteger value1, UInteger value2, Double value3, UInteger value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductPriceForOrderRecord
     */
    public ProductPriceForOrderRecord() {
        super(ProductPriceForOrder.PRODUCT_PRICE_FOR_ORDER);
    }

    /**
     * Create a detached, initialised ProductPriceForOrderRecord
     */
    public ProductPriceForOrderRecord(UInteger productId, UInteger orderId, Double pricePerProduct, UInteger quantity, Timestamp createdAt, Timestamp updatedAt) {
        super(ProductPriceForOrder.PRODUCT_PRICE_FOR_ORDER);

        set(0, productId);
        set(1, orderId);
        set(2, pricePerProduct);
        set(3, quantity);
        set(4, createdAt);
        set(5, updatedAt);
    }
}
